/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpr.doit.view;

import br.ufpr.doit.model.Task;

/**
 *
 * @author soneg
 */
public class Tarefa extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Tarefa(Task tarefa) {
        initComponents();
        setCampos(tarefa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTarefa = new javax.swing.JPanel();
        jLabelTarefa = new javax.swing.JLabel();
        jLabelExcluir = new javax.swing.JLabel();
        jLabeDone = new javax.swing.JLabel();
        jLabelImportante = new javax.swing.JLabel();

        jPanelTarefa.setBackground(new java.awt.Color(44, 62, 80));
        jPanelTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelTarefaMouseReleased(evt);
            }
        });

        jLabelTarefa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTarefa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTarefa.setText("Tarefa");

        jLabelExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/doit/view/icons8_trash_32px_2.png"))); // NOI18N
        jLabelExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelExcluirMouseReleased(evt);
            }
        });

        jLabeDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/doit/view/icons8_checkmark_26px.png"))); // NOI18N
        jLabeDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabeDoneMouseReleased(evt);
            }
        });

        jLabelImportante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufpr/doit/view/icons8_important_property_32px.png"))); // NOI18N
        jLabelImportante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelImportanteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarefaLayout = new javax.swing.GroupLayout(jPanelTarefa);
        jPanelTarefa.setLayout(jPanelTarefaLayout);
        jPanelTarefaLayout.setHorizontalGroup(
            jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImportante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeDone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExcluir)
                .addContainerGap())
        );
        jPanelTarefaLayout.setVerticalGroup(
            jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImportante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelImportanteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImportanteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImportanteMouseReleased

    private void jLabeDoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeDoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabeDoneMouseReleased

    private void jLabelExcluirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExcluirMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExcluirMouseReleased

    private void jPanelTarefaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTarefaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTarefaMouseReleased
    
    public void setCampos(Task tarefa){
        jLabelTarefa.setText(tarefa.getNome());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeDone;
    private javax.swing.JLabel jLabelExcluir;
    private javax.swing.JLabel jLabelImportante;
    private javax.swing.JLabel jLabelTarefa;
    private javax.swing.JPanel jPanelTarefa;
    // End of variables declaration//GEN-END:variables
}
